.build:
    stage: build
    except:
        - merge_requests

build-react:
    extends: .build
    image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/arm64v8/node:17.9-alpine
    script:
        - npm ci
        - npm run build
    artifacts:
        expire_in: 10 min
        paths:
            - build/
    cache:
        key: $CI_COMMIT_REF_SLUG
        paths:
            - .npm

build-image:
    extends: .build
    tags:
        - shell
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker buildx b -t $CI_REGISTRY_IMAGE:$VERSION -t $CI_REGISTRY_IMAGE:latest --platform linux/arm64 -f ci/Dockerfile.prod --push .
        # - docker rmi $CI_REGISTRY_IMAGE:$VERSION $CI_REGISTRY_IMAGE:latest
    after_script:
        - docker logout
    needs:
        - job: get-version
          artifacts: true
        - job: build-react
          artifacts: true
