#####################################
# TEMPLATES
#####################################

.merge-request:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:18.15-alpine
  cache:
    paths:
      - web/node_modules
  only:
    - merge_requests

#####################################
# JOBS
#####################################

install-react:
  extends: .merge-request
  stage: build
  script:
    - cd web
    - npm install

lint-code:
  extends: .merge-request
  stage: test
  before_script:
    - cd web
    - npm install eslint
  script:
    - npm run lint
  needs:
    - job: install-react
