variables:
  PIPELINE_NAME: Exécution (╯°□°）╯︵ ┻━┻

############################
## JOBS
############################

include:
  - project: 'labo/cicd-templates'
    ref: master
    file:
      - '/templates/deploy-swarm.gitlab-ci.yml'
  - local: ci/pipelines/merge-requests.gitlab-ci.yml
  - local: ci/pipelines/deployment.gitlab-ci.yml

############################
## WORKFLOW
############################

workflow:
  name: $PIPELINE_NAME
  rules:
    # Merge request
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        PIPELINE_NAME: "🪛 [MR] Check : $CI_COMMIT_REF_NAME"
    # Manual on master
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
      variables:
        PIPELINE_NAME: "🚀 [PROD] Deploy LATEST"
    # Manual on tags
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      variables:
        PIPELINE_NAME: "💥 [PROD] Deploy $CI_COMMIT_TAG"
    # Manual in development mode
    - if: $CI_PIPELINE_SOURCE == "web"
      variables:
        PIPELINE_NAME: "🚚 [DEV] Deploy STAGING"
    - when: never
