get-version:
    stage: .pre
    tags:
        - shell
    script:
        - ci/scripts/version.sh
    artifacts:
        reports:
            dotenv: build.env

include:
    - local: 'ci/pipelines/merge-requests.gitlab-ci.yml'
    - local: 'ci/pipelines/builds.gitlab-ci.yml'
    - local: 'ci/pipelines/dev.gitlab-ci.yml'
    - local: 'ci/pipelines/prod.gitlab-ci.yml'

workflow:
    rules:
        - if: $CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == "develop"
          when: always
        - when: never
