version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: ldapain
    env_file:
      - .env.local
    stdin_open: true
    volumes:
      - ./api:/ldapain/api
      - ./web/src:/ldapain/src
      - ./web/public:/ldapain/public
      - ./web/node_modules:/ldapain/node_modules
